### ISSUE TITLE
Calibration values not stored

### ISSUE THREAD

**Issue by tmh88** [JamesSwift/localbytes-plug-pm#1]
Good evening,

I have been trying your firmware and have noticed when you calibrate the data through HA, the calibration data is lost when power cycling the plug

Thanks

**Comment by JamesSwift** [comment]
Hmm, that's odd. My data is restored after a power cycle. 

When you calibrate it, how soon after are you power cycling? I wonder if the esp hasn't had time to write the data to flash storage (it batches the changes and only writes periodically to avoid degrading the memory). Once it's written, it should be restored though. Can you try again and walk me through the timing?

I'm not 100% clear on how the number component works on the lower level, but I was under the impression that home assistant and the esp negotiated the value together, rather than relying on just the esp to store it.

**Comment by tmh88** [comment]
Hi James,

maybe I hadn’t left them long enough, I assumed the values were saved to the flash memory when you changed the value.

I will test again later today

Thanks

**Comment by JamesSwift** [comment]
Hi @tmh88 . Did you have any success?
